from django.shortcuts import render

# Create your views here.

def courses(request):
    categories={'Information Technology':{'Artificial Intelligence and Machine Learning':'https://www.bing.com/th?id=OIP.aetQjU_NLxcf37riUl58BAHaEs&w=314&h=198&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Cloud Computing':'https://www.bing.com/th?id=OIP.9z9O3VEB60B2O_skhrgEHAHaFb&w=132&h=100&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Blockchain':'https://www.bing.com/th?id=OIP.2zosKenSVPZKUTCb3bYrRAHaFO&w=297&h=210&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Internet of Things':'https://www.bing.com/th?id=OIP.6P07FRLW8pH_-e3f8efqVgHaD7&w=343&h=182&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Digital Marketing':'https://www.bing.com/th?id=OIP.4l7wwjzvD7-joMURVOv4jAHaEd&w=322&h=193&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Networking':'https://www.bing.com/th?id=OIP.HcrdTVyMYpMvyXnpLpapCQHaE8&w=306&h=204&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Data Science':'https://th.bing.com/th/id/OIP.VWLpAjBJ3Ckr-DRxfs4tpAHaEH?w=288&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7',
    'Full-stack development':'https://th.bing.com/th/id/OIP.4W1AQGSrds4Fa63nNPzVFwHaE8?w=236&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7','Project Management':'https://th.bing.com/th/id/OIP.Bt0BxZWGRHMAnK1cmU_-MAHaE3?w=263&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7'},
    'Electronics & Communication':{'Home Automation using IoT':'https://www.bing.com/th?id=OIP.dXb1thHjZGu1VB_pUkJziwHaE5&w=168&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2',' Smart Energy Meter using GSM':'https://www.bing.com/th?id=OIP.UpaE1qM9_-wYSzM8s4AegQHaHa&w=167&h=170&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2',' Solar & Smart Energy Systems':'https://www.bing.com/th?id=OIP.67NwUtZpYRKb0TkeIWqhmQGDCh&w=266&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2',' Automatic Solar Tracker':'https://www.bing.com/th?id=OIP.YrCmJRXMa6jhPkMtaD8V7gHaE7&w=136&h=100&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2','Arduino Projects':'https://www.bing.com/th?id=OIP.sGrloJUHEJn4Jxq8wQsvsQHaEK&w=259&h=160&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2',' Smart Energy Projects':'https://www.bing.com/th?id=OIP.nVH28ZghMjy2P25NevKpPQHaEK&w=164&h=108&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2',' PCB Manufacturing':'https://www.bing.com/th?id=OIP.nSeXre9kxawR0ikKFmRkZwHaE5&w=137&h=100&c=8&rs=1&qlt=90&o=6&dpr=1.25&pid=3.1&rm=2',' Circuit Design with Proteus':'https://th.bing.com/th/id/OIP.CstMGZ1sb1xdKTHn4cQd7AHaFb?w=231&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7',' Smart Traffic Lighting System':'https://th.bing.com/th/id/OIP.tBrw_mxy9n2uhuUj1f9hzwHaF8?w=208&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7'},
    'Mechanical Engineering':{'Piping Design and Manufacturing':'https://th.bing.com/th/id/OIP.0oZXqrB9d72dHJ0T3SSBkQHaFJ?w=249&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7','Robotics':'https://th.bing.com/th/id/OIP.K_BJ-7FzlwMb4PssF-HJGQHaEh?w=314&h=192&c=7&r=0&o=5&dpr=1.25&pid=1.7','Master of Engineering in Tool Design':'https://th.bing.com/th/id/OIP.B5f4VycCpSPFRPPX2RCAOwHaFj?w=227&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7','Mechatronics Course':'https://th.bing.com/th/id/OIP.A7Zi742CbX36vGpvxKSpVwHaDt?w=350&h=175&c=7&r=0&o=5&dpr=1.25&pid=1.7','Nanotechnology Engineering':'https://th.bing.com/th/id/OIP.TbLkc23XPTkX3qNqmsb1fwHaE7?w=236&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7'},
    'Chemical Engineering':{'chemistry and technology for sustainability':'https://th.bing.com/th/id/OIP.bHV3QSKY_K-aXBwMm3aeCAHaEg?w=281&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7','plastics in infrastructure and environment':'https://th.bing.com/th/id/OIP.YPTAHXjxFHlTwsOdA7bsxAAAAA?w=261&h=159&c=7&r=0&o=5&dpr=1.25&pid=1.7','Introduction to solid state chemistry':'https://th.bing.com/th/id/OIP.1kbffVn9qprCgI12Osu0ygHaFj?w=234&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7','water and wastwater treatment(biochemical technology)':'https://th.bing.com/th/id/OIP.ogmHvXxZF38ZQpMBxOrU2AHaDc?w=324&h=163&c=7&r=0&o=5&dpr=1.25&pid=1.7','water and wastwater treatment(physicochemical technology)':'https://th.bing.com/th/id/OIP.lqGdLx6N3KfT2vkI4KIAoQHaFh?w=254&h=189&c=7&r=0&o=5&dpr=1.25&pid=1.7','micro and nanofabrication(MEMS)':'https://th.bing.com/th/id/OIP.Hn_V_RGJwRaQ4drlR-V8UQHaFj?w=226&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7'}}
    
    id=[1,2,3,4]
    return render(request,'eduApp/Courses.html',{'categories':categories,'id':id})

def aiml(request):
    return render(request,'eduApp/aiml.html')

def about(request):
    return render(request,'eduApp/about1.html')


# eccourses =['Home Automation using IoT',' Smart Energy Meter using GSM',' Solar & Smart Energy Systems',' Automatic Solar Tracker','5 Arduino Projects',' 4 Smart Energy Projects',' PCB Manufacturing',' Circuit Design with Proteus',' Smart Traffic Lighting System']


# eeelinks = ['https://www.hindawi.com/journals/scn/2021/1723535/?msclkid=fd8da170b45b115b46b6c311c201369d&utm_source=bing&utm_medium=cpc&utm_campaign=HDW_MRKT_GBL_SUB_BNGA_PAI_DYNA_JOUR_X_PJ_GROUP3&utm_term=Electrical%20and%20Computer%20Engineering&utm_content=JOUR_X_PJ_GROUP3_JECE',' Smart Traffic Lighting System','https://www.skyfilabs.com/online-courses/automatic-solar-tracker','https://www.skyfilabs.com/online-courses/5-arduino-projects','https://www.skyfilabs.com/online-courses/4-smart-energy-projects','https://www.skyfilabs.com/online-courses/pcb-manufacturing','https://www.skyfilabs.com/online-courses/circuit-design-with-proteus-live-online','https://www.skyfilabs.com/online-courses/smart-traffic-lighting-system','https://www.skyfilabs.com/online-courses/automation-using-plc']

# eccprojects=['Wireless Communication','animatronic hand','robotic arm','sensor guided robotics','automatic solar tracker','GBS and GSM based tracking','automated railway crossing']

# eeclinks =['https://www.bing.com/search?q=wireless+communication&cvid=191bed6d9e5d4e35a4536190a665baf6&aqs=edge.0.0l9.3111j0j1&pglt=43&FORM=ANNTA1&PC=HCTS','https://www.irjet.net/archives/V3/i5/IRJET-V3I5311.pdf','https://www.wellpcb.com/robotic-arm-roject.html','https://easychair.org/publications/preprint_open/V6Fg','https://rcciit.org/students_projects/projects/aeie/2019/GR2.pdf','https://bestengineeringprojects.com/gps-and-gsm-based-vehicle-tracking-system/','https://www.irjet.net/archives/V7/i3/IRJET-V7I3220.pdf']

# chemical_eng_course=['chemistry and technology for sustainability','plastics in infrastructure and environment','introduction to solid state chemistry','micro and nanofabrication(MEMS)','water and wastwater treatment(biochemical technology)','water and wastwater treatment(physicochemical technology)']
# courselinks=['https://ebook.mediadata.website/solid-state-chemistry-an-introduction.pdf','https://www.edx.org/es/course/plastics-in-infrastructure-and-the-environment','https://ocw.mit.edu/courses/3-091sc-introduction-to-solid-state-chemistry-fall-2010/','https://www.edx.org/course/micro-and-nanofabrication-mems','https://www.slideshare.net/alexandrenm/water-and-wastewater-treatment-biochemical-technology','https://www.researchgate.net/publication/306088427_Physico-Chemical_Waste_Water_Treatment_Technologies_An_Overview']
